apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu-node
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: besu
  template:
    metadata:
      labels:
        app: besu
    spec:
      containers:
      - name: besu
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: 8545
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: besu-pvc
