# Network settings
network = "dev"
data-path = "../data/node1"
genesis-file = "../config/genesis.json"
p2p-host = "127.0.0.1"
p2p-port = 30303
rpc-http-enabled = true
rpc-http-host = "127.0.0.1"
rpc-http-port = 8545
rpc-http-api = ["ETH", "NET", "WEB3"]
rpc-ws-enabled = true
rpc-ws-host = "127.0.0.1"
rpc-ws-port = 8546
rpc-ws-api = ["ETH", "NET", "WEB3"]
metrics-enabled = true
metrics-host = "127.0.0.1"
metrics-port = 9545
host-allowlist = ["*"]
engine-jwt-secret = "../config/jwt-secret.hex"
