global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'besu'
    static_configs:
      - targets: ['localhost:9545']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'web3auth'
    static_configs:
      - targets: ['localhost:9546']
    metrics_path: '/metrics'
