name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTRACTS_FOLDER: './contracts'
  FRONTEND_FOLDER: './frontend'
  SAFE_ADDRESS: ${{ secrets.SAFE_ADDRESS }}
  SAFE_SERVICE_URL: ${{ secrets.SAFE_SERVICE_URL }}
  RPC_URL: ${{ secrets.RPC_URL }}
  DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
  CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd $CONTRACTS_FOLDER
          npm install
          cd ../$FRONTEND_FOLDER
          npm install

      - name: Run Tests
        run: |
          cd $CONTRACTS_FOLDER
          npm test
          cd ../$FRONTEND_FOLDER
          npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy Contracts
        run: |
          cd $CONTRACTS_FOLDER
          npm install
          npx hardhat deploy --network mainnet \
            --safe-address ${{ env.SAFE_ADDRESS }} \
            --safe-service-url ${{ env.SAFE_SERVICE_URL }} \
            --rpc-url ${{ env.RPC_URL }} \
            --private-key ${{ env.DEPLOYER_KEY }}

      - name: Build Frontend
        run: |
          cd $FRONTEND_FOLDER
          npm install
          npm run build
          
      - name: Deploy Frontend
        env:
          CONTRACT_ADDRESS: ${{ env.CONTRACT_ADDRESS }}
        run: |
          cd $FRONTEND_FOLDER
          npm run deploy
