name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTRACTS_FOLDER: './contracts'
  FRONTEND_FOLDER: './frontend'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd ${{ env.CONTRACTS_FOLDER }}
          npm install
          cd ../${{ env.FRONTEND_FOLDER }}
          npm install

      - name: Run Tests
        run: |
          cd ${{ env.CONTRACTS_FOLDER }}
          npm test
          cd ../${{ env.FRONTEND_FOLDER }}
          npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy Contracts
        env:
          SAFE_ADDRESS: ${{ secrets.SAFE_ADDRESS }}
          SAFE_SERVICE_URL: ${{ secrets.SAFE_SERVICE_URL }}
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
        run: |
          cd ${{ env.CONTRACTS_FOLDER }}
          npm install
          cat > .env << EOL
          SAFE_ADDRESS=$SAFE_ADDRESS
          SAFE_SERVICE_URL=$SAFE_SERVICE_URL
          RPC_URL=$RPC_URL
          DEPLOYER_KEY=$DEPLOYER_KEY
          EOL
          npx hardhat deploy --network mainnet

      - name: Build Frontend
        run: |
          cd ${{ env.FRONTEND_FOLDER }}
          npm install
          npm run build
          
      - name: Deploy Frontend
        env:
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
        run: |
          cd ${{ env.FRONTEND_FOLDER }}
          echo "CONTRACT_ADDRESS=$CONTRACT_ADDRESS" > .env
          npm run deploy
